# Generated by Django 4.2.3 on 2023-11-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'کد نخفیف', 'verbose_name_plural': 'کد تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='itemorder',
            options={'verbose_name': 'خریداری شده', 'verbose_name_plural': 'خریداری شده'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارشات', 'verbose_name_plural': 'سفارشات'},
        ),
    ]
