# Generated by Django 4.2.3 on 2023-11-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_color_size_product_status_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Size', 'size'), ('Color', 'color'), ('Both', 'Both')], max_length=200, null=True),
        ),
    ]
