# Generated by Django 4.2.3 on 2023-12-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_sliderfirst'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderfirst',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر'},
        ),
    ]
